- hosts: all
  become: true
  tasks:
    - name: Installer Apache2
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Déployer la page Hello World
      copy:
        dest: /var/www/html/index.html
        content: "<html><h1>Hello World</h1></html>"
        mode: "0644"

    - name: Démarrer le service Apache2
      service:
        name: apache2
        state: started
        enabled: true
