version: "3.9"

services:
  database:
    build:
      context: ./database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: ./backendAPI/simple-api-student-main
    container_name: simple-api-students-main
    restart: "on-failure"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
      - proxy-network

  httpd:
    build:
      context: ./http-server
    ports:
      - "80:80"
    depends_on: 
      - backend
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  app-network: {}
  proxy-network: {}

volumes:
  pgdata: {}
