- name: Run database container
  docker_container:
    name: database
    image: oxygenzoo/tp-devops-database:latest
    env:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    networks:
      - name: my_network
    state: started
    restart_policy: always

